<div class="field is_trainer required">
    <label class="label" for="is_trainer">
      	<span><?= $block->escapeHtml(__('Do You Want To Register as Trainer?')) ?></span>
    </label>
    <div class="control">
    	<input type="radio" id="trainer" class="wantpartner" name="is_trainer" value="1" title="Agree as Trainer">Yes
        <input type="radio" id="trainer0" class="wantpartner" name="is_trainer" value="0" title="Disagree as Trainer" checked="">No
    </div>
</div>