<div class="field mobile_number required">
   <label class="label" for="mobile_number">
       <span><?= $block->escapeHtml(__('Mobile number')) ?></span>
   </label>
   <div class="control">
       <input type="text" name="mobile_number" id="mobile_number" value="" title="<?= $block->escapeHtmlAttr(__('Mobile number')) ?>" class="input-text" data-validate="{required:true}">
   </div>
</div>