<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php $InstockLable = $block->getInstockLable(); ?>
<?php $lowseatLable = $block->getLabelforLowseats(); ?>
<?php $lowseatNumber = $block->getLabelforLowseatsnumber(); ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i=0; ?>
            <?php foreach ($_productCollection as $_product): ?>
            
            <!-- Added code -->
            <?php 
                $i++; 
                $customerDetails = $block->getCustomerDetails($_product->getData('customer_id'));
            ?>
            <!-- Added code -->

            <li class="item product product-item" style="margin-bottom: 12px; background-color: white;">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    
                    <div class="product details product-item-details" style="padding: 20px;">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        
                        <!-- shifted html start here -->
                        <div class="actions-primary" style="float: right;">
                            <?php if ($_product->isSaleable()):?>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form"
                                    data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                    action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                    data-mage-init='{"catalogAddToCart": {}}'
                                    method="post">
                                <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                <?php foreach ($options as $optionItem): ?>
                                    <input type="hidden"
                                            name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                            value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                <?php endforeach; ?>
                                <input type="hidden"
                                        name="product"
                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                <input type="hidden"
                                        name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                        value="<?=
                                        /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                        ?>">
                                <?= $block->getBlockHtml('formkey') ?>
                                <button type="submit"
                                        title="<?= $escaper->escapeHtmlAttr(__('Enroll Now')) ?>"
                                        class="action tocart primary"
                                        disabled>
                                    <span><?= $escaper->escapeHtml(__('Enroll Now')) ?></span>
                                </button>
                            </form>
                            <?php else:?>
                            <?php if ($_product->isAvailable()):?>
                            <div class="stock available">
                                <span><?= $escaper->escapeHtml(__('Available')) ?></span>
                            </div>
                            <?php else:?>
                            <div class="stock unavailable">
                                <span><?= $escaper->escapeHtml(__('Unavailable')) ?></span>
                            </div>
                            <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <!-- shifted html end here -->

                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <strong>
                                <?php $prodObj = $_product->load($_product->getId()); ?>
                                <?php $stockItem = $prodObj->getExtensionAttributes()->getStockItem(); ?>
                                <?php $ProductQty = $stockItem->getQty(); ?>
                                <?php if ($ProductQty > $lowseatNumber) : ?>
                                    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                        <span><?= $InstockLable ?></span>
                                    </div>
                                <?php else : ?>
                                    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                        <span><?= $lowseatLable ?></span>
                                    </div>
                                <?php endif; ?>
                            </strong>

                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                        <!-- added html start here -->
                        <div class="extra_content_here">
                        <?php if($_product->getAttributeText('type_of_course_attribute') == 'Live Training') { ?>
                            <p class="date_info">
                                <?= $block->getFormatedDate($_product->getData('course_start_date'), 'M d') ?> - <?= $block->getFormatedDate($_product->getData('course_end_date'), 'M d') ?>, <label class="batch-type"><?= $_product->getData('availability_attribute') ?></label>
                            </p>
                            <p class="batch_info">
                                <?= $_product->getData('batch_start_time') . "-" . $_product->getData('batch_end_time') ?>, (<?= $block->getTimeZone(); ?>)
                            </p>
                            <p class="course-type"><label>Course Type: </label>
                                <?= $_product->getAttributeText('type_of_course_attribute') ?>
                            </p>
                            <?php if($customerDetails) { ?>
                            <p class="trainer"><label>Training Provide By: </label>
                                <?= $customerDetails->getfirstname() ." ". $customerDetails->getlastname() ?>
                            </p>
                            <?php }}else{ ?>
                            <p class="course-type"><label>Course Type: </label>
                                <?= $_product->getAttributeText('type_of_course_attribute') ?> <span>(Downloadable Course)</span>
                            </p>
                            <?php if($customerDetails) { ?>
                            <p class="trainer"><label>Course Provide By: </label>
                                <?= $customerDetails->getfirstname() ." ". $customerDetails->getlastname() ?>
                            </p>
                            <?php }} ?>
                        </div>
                          
                        <!-- added html ended here -->

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <!-- added html start here --------------------------------------------------- -->
                        <?php if($_product->getAttributeText('type_of_course_attribute') == 'Live Training') { ?>
                        <div class="more_course_detail">
                            <div class="btn_moredetail">
                                <button type="button" pickval="<?php echo $i; ?>" id="btn-reveal-<?php echo $i; ?>" class="btn btn_reveal">More Detail</button>
                            </div>
                        
                            <div class="toggle_wrapper" id="toggle-wrapper-<?php echo $i; ?>">
                                <div class="product-more-details">
                                    <hr>
                                    <div class="delivery_mode">
                                    
                                        <span class="more_detail_title_span">MODE OF DELIVERY & TRAINER</span>
                                        <p></p>
                                        <p class="course-type">
                                            <?= $_product->getAttributeText('type_of_course_attribute') ?>
                                        </p>
                                        <p class="date_info">
                                            <?= $block->getFormatedDate($_product->getData('course_start_date'), 'M d') ?> - <?= $block->getFormatedDate($_product->getData('course_end_date'), 'M d') ?>
                                        </p>
                                        <p class="batch_info">
                                            <?= $_product->getData('batch_start_time') . "-" . $_product->getData('batch_end_time')?>, (<?= $block->getTimeZone(); ?>)
                                        </p>
                                    </div>
                                    <div class="trainer_info">
                                        <span class="more_detail_title_span">TRAINER</span>
                                        <p></p>
                                        <?php if($customerDetails) { ?>
                                        <p class="trainer_name">
                                            <?= $customerDetails->getfirstname() ." ". $customerDetails->getlastname() ?>
                                        </p>
                                        <?php } ?>
                                    </div>
                                    <?php 
                                        $scheduleDetails = $block->getCourseSchedule($_product->getData('course_start_date'), $_product->getData('course_end_date'));                                                     
                                    ?>

                                    <div class="schedule_info">
                                        <span class="more_detail_title_span">SCHEDULES</span><span class="font_18"> (<?= empty($_product->getData('availability_attribute')) ? '' : strtoupper($_product->getData('availability_attribute')); ?> BATCH) <?php echo count($scheduleDetails) . " Days"; ?></span>
                                        <p></p>
                                        <p class="course-schedule">
                                            <?php    
                                                foreach($scheduleDetails as $schedule) {
                                                    echo $schedule . "      |      ";
                                                }
                                            ?>
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <?php } ?>
                        <!--  added html end here ------------------------------------------------- -->

                    </div>
                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<?php endif; ?>
   
<style>
     /* Css Added for listing Page */

 #maincontent{
    background-color: #d3d3d378;
}

.btn_moredetail {
    text-align: center;
}

.product-more-details {
    margin-top: 40px;
}

.delivery_mode {
    float: left;
    width: 50%;
}

.schedule_info {
    float: left;
    width: 100%;
    margin-top: 40px;
}

.more_detail_title_span {
    font-size: 16px;
    color: darkgray;
}

.font_18 {
    font-size: 16px;
    font-weight: 600;
}

.trainer_name {
    font-size: 14px;
    font-weight: 700;
    color: #26d400;
}

.date_info, .batch_info, .trainer {
    font-size: 14px;
    font-weight: 700;
    color: #000000b3;
} 

.toggle_wrapper {
    display: none;
}
</style>

<script>
    require(
        [
            'jquery',
        ],
      function($) {
        $('.btn_reveal').click(function() {
            let divId = $(this).attr('pickval');

            if($('#toggle-wrapper-'+divId).css('display') == 'block') {
                $(this).text('More Detail');
            } else {
                $(this).text('Less Detail');
            }

            $('#toggle-wrapper-'+divId).toggle('slow');
        });
      }
  );
</script>