<?php
$MobileNumber = $block->getCustomer()->getCustomAttribute('mobile_number');
$customerMobileNumber = $MobileNumber ? $MobileNumber->getValue() : null;
?>
<fieldset class="fieldset create account" >
    <legend class="legend">
        <span><?=$block->escapeHtmlAttr(__('Mobile Number'))?></span>
    </legend>
    <br>
    <div class="field mobile_number">
        <label for="mobile_number" class="label">
            <span><?=$block->escapeHtmlAttr(__('Mobile Number'));?></span>
        </label>
        <div class="control">
            <input id="mobile_number" 
                   class="input-text" 
                   name="mobile_number" 
                   value="<?=$block->escapeHtmlAttr($customerMobileNumber);?>" 
                   title="<?=$block->escapeHtmlAttr(__('Mobile Number'));?>" 
                   type="text" 
                   autocomplete="off" />
        </div>
    </div>
</fieldset>